### ISSUE TITLE
Integration of the registration page to the Pod UI

### ISSUE THREAD

**Issue by joeitu** [solid/community-server-recipes#6]
Hello, 

In the following, I'll refer to *UI* as general User Interface, and by *Pod UI* I'll refer to a specific kind of solid app build to deliver a UI for a solid pod ( like penny or mashlib ) . I'll refer to SCS for the solid community server and CSS for Cascading Style Sheet.

On the recipes, we can see a difference in UI between the SCS registration page and the pod UI. Moreover, both Pod UIs don't provide links to SCS registration page. 

I'm wondering what is the correct solution to unify those two interfaces that live under the same URL.

A solution would be to unify the CSS of both, and modify their HTML so they can share the same navbar.

Another solution would be to drop the pages from SCS, and create new pages on the Pod UIs side that handle the registration process by consuming SCS API. Then they would be naturally under the same CSS rules, and a link to the registration page can be added to the Pod UI. 
It seems that no current Pod UIs have such a feature, is there a reason? 

In both of the above solutions,  the Pod UI cannot be simply imported through npm and glued to SCS in components.js, we need to edit their source code which is slightly annoying. Is there other possible solutions?

**Comment by RubenVerborgh** [comment]
> I'm wondering what is the correct solution to unify those two interfaces that live under the same URL.

So server itself supports this: there folder for templates (HTML) and assets (CSS, images) can be freely configured. So the default CSS interfaces for pod registration can be adjusted.

> A solution would be to unify the CSS of both, and modify their HTML so they can share the same navbar.
> 
> Another solution would be to drop the pages from SCS, and create new pages on the Pod UIs side that handle the registration process by consuming SCS API.

Both of these are possible, really. It's up to what you think is the least amount of work.

> It seems that no current Pod UIs have such a feature, is there a reason?

Because the registration API is not standardized. If it is, then we can write custom apps that do registration.

> we need to edit their source code which is slightly annoying. Is there other possible solutions?

That's something that needs to be addressed in the Pod UIs; they would need to be written in a more modular way.
Perhaps they can export a "host" page, in which the CSS content can be inserted?
E.g., I do this on my own website as well: a [blank frame](https://ruben.verborgh.org/empty/), to which apps can insert their content.

**Comment by RubenVerborgh** [comment]
The server does have the "specification" indeed: it is the current JSON API, which is implemented in https://github.com/solid/community-server/tree/982d57e1d2812925b09353445a318d067a242943/templates/identity/email-password
